import {
  Ban,
  Building2,
  ClipboardCheck,
  Clock3,
  GraduationCap,
  IndianRupee,
  ShieldCheck,
  TrendingUp,
  UsersRound,
} from "lucide-react";
import type { ScholarLearnDashboardData } from "../types/scholarLearn.types";

export const scholarLearnDemoDashboardData: ScholarLearnDashboardData = {
  activeInactiveGraph: [
    { active: 24, inactive: 2, label: "Jan" },
    { active: 27, inactive: 2, label: "Feb" },
    { active: 30, inactive: 3, label: "Mar" },
    { active: 33, inactive: 3, label: "Apr" },
    { active: 36, inactive: 4, label: "May" },
    { active: 39, inactive: 3, label: "Jun" },
  ],
  activities: [
    {
      description: "Fengari Institute Hyderabad renewed the Premium subscription for 12 months.",
      id: "activity-renewal",
      time: "Today, 9:40 AM",
      title: "Subscription renewed",
    },
    {
      description: "Founder approvals are trending down after the weekly access review.",
      id: "activity-approvals",
      time: "Yesterday, 5:10 PM",
      title: "Approval queue improved",
    },
    {
      description: "Student test attempts completed successfully across active institutes.",
      id: "activity-tests",
      time: "Mon, 3:25 PM",
      title: "Test platform stable",
    },
  ],
  attendanceTestSummary: [
    { attendance: 84, label: "Jan", tests: 74 },
    { attendance: 86, label: "Feb", tests: 76 },
    { attendance: 88, label: "Mar", tests: 79 },
    { attendance: 87, label: "Apr", tests: 81 },
    { attendance: 90, label: "May", tests: 83 },
    { attendance: 91, label: "Jun", tests: 85 },
  ],
  instituteGrowthGraph: [
    { growth: 280, label: "Jan", students: 1220 },
    { growth: 330, label: "Feb", students: 1324 },
    { growth: 420, label: "Mar", students: 1438 },
    { growth: 470, label: "Apr", students: 1510 },
    { growth: 520, label: "May", students: 1586 },
    { growth: 590, label: "Jun", students: 1674 },
  ],
  institutePerformanceGraph: [
    { label: "Fengari HYD", performance: 88 },
    { label: "Fengari BLR", performance: 84 },
    { label: "Fengari PUNE", performance: 76 },
    { label: "Fengari CHN", performance: 81 },
    { label: "Fengari VIZ", performance: 72 },
  ],
  institutes: [
    {
      activeBatches: 18,
      activeRemainingDays: 278,
      averageAttendance: 91,
      averagePerformance: 88,
      branches: 4,
      city: "Hyderabad",
      disabled: false,
      expiryDate: "2027-04-05",
      founderEmail: "founder@fengari.me",
      founderName: "Chaitanya Pilla",
      handle: "@fengari-hyd",
      id: "fengari-hyd",
      name: "Fengari Institute Hyderabad",
      ownerPgs: [
        { batches: 6, city: "Madhapur", id: "hyd-madhapur", name: "Madhapur PG Campus", status: "Active", students: 286 },
        { batches: 5, city: "Kukatpally", id: "hyd-kukatpally", name: "Kukatpally PG Campus", status: "Active", students: 214 },
        { batches: 4, city: "Ameerpet", id: "hyd-ameerpet", name: "Ameerpet PG Campus", status: "Active", students: 188 },
        { batches: 3, city: "Gachibowli", id: "hyd-gachibowli", name: "Gachibowli PG Campus", status: "Maintenance", students: 136 },
      ],
      plan: "Yearly",
      startDate: "2025-04-05",
      status: "Active",
      students: 824,
      totalLecturers: 42,
    },
    {
      activeBatches: 12,
      activeRemainingDays: 164,
      averageAttendance: 86,
      averagePerformance: 84,
      branches: 3,
      city: "Bengaluru",
      disabled: false,
      expiryDate: "2026-12-11",
      founderEmail: "blr.founder@fengari.me",
      founderName: "Ananya Rao",
      handle: "@fengari-blr",
      id: "fengari-blr",
      name: "Fengari Institute Bengaluru",
      ownerPgs: [
        { batches: 5, city: "Marathahalli", id: "blr-marathahalli", name: "Marathahalli PG Campus", status: "Active", students: 206 },
        { batches: 4, city: "BTM Layout", id: "blr-btm", name: "BTM Layout PG Campus", status: "Active", students: 184 },
        { batches: 3, city: "Whitefield", id: "blr-whitefield", name: "Whitefield PG Campus", status: "Active", students: 122 },
      ],
      plan: "Yearly",
      startDate: "2025-12-11",
      status: "Active",
      students: 512,
      totalLecturers: 31,
    },
    {
      activeBatches: 7,
      activeRemainingDays: 41,
      averageAttendance: 78,
      averagePerformance: 76,
      branches: 2,
      city: "Pune",
      disabled: false,
      expiryDate: "2026-08-10",
      founderEmail: "pune.founder@fengari.me",
      founderName: "Rahul Menon",
      handle: "@fengari-pune",
      id: "fengari-pune",
      name: "Fengari Institute Pune",
      ownerPgs: [
        { batches: 4, city: "Hinjewadi", id: "pune-hinjewadi", name: "Hinjewadi PG Campus", status: "Active", students: 168 },
        { batches: 3, city: "Kothrud", id: "pune-kothrud", name: "Kothrud PG Campus", status: "Active", students: 118 },
      ],
      plan: "Monthly",
      startDate: "2025-08-10",
      status: "Trial",
      students: 286,
      totalLecturers: 18,
    },
    {
      activeBatches: 0,
      activeRemainingDays: 0,
      averageAttendance: 0,
      averagePerformance: 0,
      branches: 1,
      city: "Chennai",
      disabled: true,
      expiryDate: "2026-05-29",
      founderEmail: "chen.founder@fengari.me",
      founderName: "Meera Iyer",
      handle: "@fengari-chn",
      id: "fengari-chn",
      name: "Fengari Institute Chennai",
      ownerPgs: [
        { batches: 0, city: "T Nagar", id: "chn-tnagar", name: "T Nagar PG Campus", status: "Disabled", students: 74 },
      ],
      plan: "Trial",
      startDate: "2026-04-29",
      status: "Expired",
      students: 74,
      totalLecturers: 6,
    },
  ],
  metrics: [
    {
      description: "Institutes currently onboarded",
      icon: Building2,
      label: "Total Institutes",
      tone: "primary",
      value: "4",
    },
    {
      description: "Institutes with active access",
      icon: ShieldCheck,
      label: "Active Institutes",
      tone: "primary",
      value: "3",
    },
    {
      description: "Founder accounts waiting for approval",
      icon: Clock3,
      label: "Pending Founder Approvals",
      tone: "orange",
      value: "7",
    },
    {
      description: "Expired or manually disabled institutes",
      icon: Ban,
      label: "Expired / Disabled",
      tone: "red",
      value: "1",
    },
    {
      description: "Students across all institutes",
      icon: UsersRound,
      label: "Total Students",
      tone: "blue",
      value: "1,696",
    },
    {
      description: "Lecturers across all institutes",
      icon: GraduationCap,
      label: "Total Lecturers",
      tone: "yellow",
      value: "97",
    },
    {
      description: "Demo fallback until revenue API connects",
      icon: IndianRupee,
      label: "Total Revenue",
      tone: "primary",
      value: "Rs 18.4L",
    },
    {
      description: "Month-over-month platform usage",
      icon: TrendingUp,
      label: "Growth",
      tone: "primary",
      value: "+18%",
    },
  ],
  planDistribution: [
    { color: "#58cc02", name: "Yearly", value: 42 },
    { color: "#1cb0f6", name: "Monthly", value: 31 },
    { color: "#ffc800", name: "Trial", value: 17 },
    { color: "#ff7a45", name: "Custom", value: 10 },
  ],
  roleHealth: [
    { activeUsers: 1450, label: "Students", pendingApprovals: 21, trend: "+12%" },
    { activeUsers: 97, label: "Lecturers", pendingApprovals: 6, trend: "+5%" },
    { activeUsers: 4, label: "Founders", pendingApprovals: 7, trend: "Review" },
    { activeUsers: 18, label: "Admins", pendingApprovals: 3, trend: "+2%" },
  ],
};
